version: '3.8'

services:
  front:
    container_name: dc-front
    build: ./front
    ports:
      - "${FRONT_PORT}:3000"
      - "24678:24678"
    volumes:
      - ./front:/app
      - ./front/node_modules
      - ./front/.nuxt
    depends_on:
      - api
  
  api:
    container_name: dc-api
    build:
      context: './api'
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./api:/app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}  # MongoDB URI

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_admin
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    ports:
      - "8081:8081"


  # api:
  #   container_name: dc-api
  #   build:
  #     context: './api'
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${API_PORT}:80"
  #   volumes:
  #     - ./api:/var/www/html
  #     - ./api/public/uploads:/var/www/public/uploads
  #     - ./api/storage:/var/www/storage
  #   depends_on:
  #     - mysql

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   env_file:
  #     - ./api/.env
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

  # phpmyadmin:
  #   ports:
  #     - "8090:80"
  #   image: phpmyadmin:latest
  #   restart: always
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   env_file:
  #     ./api/.env
  #   depends_on:
  #     - mysql

volumes:
  db_data:
    driver: local